"""baseline

Revision ID: 08d07f84aa66
Revises:
Create Date: 2026-03-12 21:14:25.526166-03:00

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '08d07f84aa66'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
